name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Install dependencies and build'
        run: |
          npm install
          npm run build --if-present

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-static-html-app-123' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_48FA4E8112284893B50DC91368E72420 }}
          package: .




